# Generated by Django 4.2.3 on 2023-07-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candiate',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
