# Generated by Django 4.2.3 on 2023-07-15 15:49

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candiate',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name=builtins.id),
        ),
    ]
