# Generated by Django 4.2.3 on 2023-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0002_candidate_awards_candidate_bachelor_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='permanentaddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='see_institute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='temporaryaddress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
