# Generated by Django 4.2.3 on 2023-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0005_alter_candidate_see_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='see_marks',
        ),
    ]
