# Generated by Django 4.2.3 on 2023-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0006_remove_candidate_see_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='see_marks',
            field=models.IntegerField(null=True),
        ),
    ]
