# Generated by Django 4.2.3 on 2023-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0008_alter_candidate_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
