# Generated by Django 4.2.3 on 2023-07-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0010_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bachelor_institute',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bachelor_marks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bachelor_transcript',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='internsip',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='permanentaddress',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='plus_two_institute',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='plus_two_marks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='plus_two_transcript',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_email_1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_email_2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_name_1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_name_2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_phone_1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='refrence_phone_2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='see_institute',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='see_marks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='see_transcript',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='temporaryaddress',
        ),
    ]
