# Generated by Django 4.2.3 on 2023-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0011_remove_candidate_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('NONE', 'None'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(default='98', max_length=20, null=True),
        ),
    ]
