# Generated by Django 4.2.3 on 2023-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0013_candidate_awards_candidate_bachelor_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
