# Generated by Django 4.2.3 on 2023-07-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0014_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrstaff',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
