# Generated by Django 4.2.3 on 2023-07-25 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0016_remove_candidate_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrstaff',
            name='autonumber',
            field=models.CharField(default='', max_length=50, null=True),
        )
       
    ]
