# Generated by Django 4.2.3 on 2023-07-25 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0017_hrstaff_autonumber_alter_hrstaff_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrstaff',
            name='autonumber',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='hrstaff',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
