# Generated by Django 4.2.3 on 2023-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0019_alter_hrstaff_autonumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='hrstaff',
            name='autonumber',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
    ]
