# Generated by Django 4.2.3 on 2023-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0020_remove_candidate_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrstaff',
            name='autonumber',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
