# Generated by Django 4.2.3 on 2023-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0021_hrstaff_autonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrstaff',
            name='autonumber',
            field=models.CharField(default='101', max_length=50, null=True),
        ),
    ]
