# Generated by Django 4.2.3 on 2023-07-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0022_alter_hrstaff_autonumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assigned_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navbackend.hrstaff'),
        ),
    ]
