# Generated by Django 4.2.3 on 2023-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0023_candidate_assigned_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
