# Generated by Django 4.2.3 on 2023-07-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0025_rename_selected_isselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isselected',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navbackend.candidate'),
        ),
    ]
