# Generated by Django 4.2.3 on 2023-07-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbackend', '0026_alter_isselected_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isselected',
            old_name='email',
            new_name='candidate',
        ),
    ]
